"""
ADIF (Amateur Data Interchange Format) log reader/writer.

Supports ADIF 3.1.x.  Each QSO is stored as a QSORecord dataclass.
The ADIFLog class maintains an in-memory list and persists to .adi file.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field, fields
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class QSORecord:
    """One QSO contact."""
    call: str = ""
    freq_khz: float = 0.0          # kHz
    band: str = ""                  # "20m", "40m", etc.
    mode: str = ""                  # "SSB", "CW", "FT8", …
    rst_sent: str = "599"
    rst_rcvd: str = "599"
    qso_date: str = ""              # YYYYMMDD
    time_on: str = ""               # HHMMSS
    time_off: str = ""
    name: str = ""
    qth: str = ""
    notes: str = ""
    tx_pwr: str = ""                # watts as string
    gridsquare: str = ""
    my_gridsquare: str = ""
    lotw_qsl_sent: str = "N"
    lotw_qsl_rcvd: str = "N"
    eqsl_qsl_sent: str = "N"
    eqsl_qsl_rcvd: str = "N"
    qsl_sent: str = "N"
    qsl_rcvd: str = "N"
    extra: dict[str, str] = field(default_factory=dict)

    @classmethod
    def now(cls, call: str = "", freq_khz: float = 0.0, mode: str = "") -> "QSORecord":
        now = datetime.now(tz=timezone.utc)
        return cls(
            call=call,
            freq_khz=freq_khz,
            mode=mode,
            qso_date=now.strftime("%Y%m%d"),
            time_on=now.strftime("%H%M%S"),
        )


# ADIF field names matching QSORecord attributes (subset)
_FIELD_MAP: dict[str, str] = {
    "CALL": "call",
    "FREQ": "freq_khz",
    "BAND": "band",
    "MODE": "mode",
    "RST_SENT": "rst_sent",
    "RST_RCVD": "rst_rcvd",
    "QSO_DATE": "qso_date",
    "TIME_ON": "time_on",
    "TIME_OFF": "time_off",
    "NAME": "name",
    "QTH": "qth",
    "COMMENT": "notes",
    "TX_PWR": "tx_pwr",
    "GRIDSQUARE": "gridsquare",
    "MY_GRIDSQUARE": "my_gridsquare",
    "LOTW_QSL_SENT": "lotw_qsl_sent",
    "LOTW_QSL_RCVD": "lotw_qsl_rcvd",
    "EQSL_QSL_SENT": "eqsl_qsl_sent",
    "EQSL_QSL_RCVD": "eqsl_qsl_rcvd",
    "QSL_SENT": "qsl_sent",
    "QSL_RCVD": "qsl_rcvd",
}


class ADIFLog:
    """In-memory QSO log backed by an ADIF file."""

    HEADER = (
        "Generated by 5trig\n"
        "<adif_ver:5>3.1.4\n"
        "<programid:6>5trig\n"
        "<EOH>\n\n"
    )

    def __init__(self, path: Path | str) -> None:
        self.path = Path(path)
        self._records: list[QSORecord] = []
        if self.path.exists():
            self._load()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def records(self) -> list[QSORecord]:
        return list(self._records)

    def add(self, qso: QSORecord) -> None:
        self._records.append(qso)
        self._append_record(qso)

    def update(self, index: int, qso: QSORecord) -> None:
        self._records[index] = qso
        self._rewrite()

    def delete(self, index: int) -> None:
        del self._records[index]
        self._rewrite()

    def worked_calls(self) -> set[str]:
        return {r.call.upper() for r in self._records}

    def export_adif(self, dest: Path) -> None:
        with dest.open("w", encoding="utf-8") as f:
            f.write(self.HEADER)
            for rec in self._records:
                f.write(self._record_to_adif(rec))

    # ------------------------------------------------------------------
    # File I/O
    # ------------------------------------------------------------------

    def _load(self) -> None:
        text = self.path.read_text(encoding="utf-8", errors="replace")
        # Skip header (everything before <EOH>)
        eoh = text.upper().find("<EOH>")
        if eoh != -1:
            text = text[eoh + 5:]
        self._records = self._parse_records(text)
        logger.info("Loaded %d QSOs from %s", len(self._records), self.path)

    def _rewrite(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("w", encoding="utf-8") as f:
            f.write(self.HEADER)
            for rec in self._records:
                f.write(self._record_to_adif(rec))

    def _append_record(self, qso: QSORecord) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("a", encoding="utf-8") as f:
            if self.path.stat().st_size == 0:
                f.write(self.HEADER)
            f.write(self._record_to_adif(qso))

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _field(name: str, value: str) -> str:
        return f"<{name}:{len(value)}>{value}\n"

    @classmethod
    def _record_to_adif(cls, qso: QSORecord) -> str:
        parts: list[str] = []
        for adif_name, attr in _FIELD_MAP.items():
            val = str(getattr(qso, attr, ""))
            if val:
                parts.append(cls._field(adif_name, val))
        for key, val in qso.extra.items():
            if val:
                parts.append(cls._field(key.upper(), val))
        parts.append("<EOR>\n\n")
        return "".join(parts)

    @staticmethod
    def _parse_records(text: str) -> list[QSORecord]:
        records: list[QSORecord] = []
        # Split on <EOR> (case insensitive)
        for block in re.split(r"<EOR>", text, flags=re.IGNORECASE):
            block = block.strip()
            if not block:
                continue
            qso = QSORecord()
            for m in re.finditer(r"<(\w+)(?::\d+(?::\w+)?)?>([^<]*)", block):
                tag = m.group(1).upper()
                value = m.group(2).strip()
                attr = _FIELD_MAP.get(tag)
                if attr:
                    try:
                        if attr == "freq_khz":
                            setattr(qso, attr, float(value))
                        else:
                            setattr(qso, attr, value)
                    except (ValueError, TypeError):
                        pass
                else:
                    qso.extra[tag] = value
            if qso.call:
                records.append(qso)
        return records
